### PR TITLE
Terraform 0.12 compatibility

### PR DESCRIPTION
**Pull request by jamestoyer**
According to https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html
this should also work with 0.10 and 0.11.

I also run the recommended commands
```
go get github.com/hashicorp/terraform@v0.12.0-rc1
go mod tidy
go mod vendor
```
However, this seems to have made a lot of changes to the vendor directory. Is this expected behaviour?

### CODE REVIEW

**Comment by tgermain** [comment]
I test your branch with Terraform v0.11.13 and it works well.

If someone can test it with terraform >=0.12.x to confirm it also works.

**Comment by charlex** [comment]
Testing and building is working for me in terraform `v0.12.0` on my local OSX machine. 

I didn't run the acceptance tests yet, but I intend to install this branch on my CircleCI debian workflow, and give `terraform-provider-circleci` a try for the first time!

```sh
make build
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -a -o terraform-provider-circleci_v0.0.1
```

```sh
make test
go test -v -cover ./...
?   	github.com/mrolla/terraform-provider-circleci	[no test files]
=== RUN   TestCircleCIEnvironmentVariableCreateThenUpdate
--- SKIP: TestCircleCIEnvironmentVariableCreateThenUpdate (0.00s)
    testing.go:461: Acceptance tests skipped unless env 'TF_ACC' set
=== RUN   TestCircleCIEnvironmentVariableCreateAlreadyExists
--- SKIP: TestCircleCIEnvironmentVariableCreateAlreadyExists (0.00s)
    testing.go:461: Acceptance tests skipped unless env 'TF_ACC' set
PASS
coverage: 3.3% of statements
```

Btw, is it apart of Makefiles that `make all` is provided by default? I couldn't run `make all` on my OSX machine, due to the target not being found.

**Comment by charlex** [comment]
I tested this on OSX (darwin) and on Debian (linux) with Terraform v0.12.0 and it is working well for me!

My usecase is for uploading env secrets to multiple CircleCI projects just FYI.

**Comment by charlex** [comment]
🎉🎉

**Comment by martyphee** [comment]
Is everyone happy with it?  When can it be merged?

**Comment by tgermain** [comment]
@mrolla what do you think ? 
Should it be merged ? If so a new release for terraform 0.12 compatibility should be created.

**Comment by tgermain** [comment]
> Sorry guys for the delay, been quite busy lately. The change LGTM, before releasing the new version though I would like to rewrite the client part to better fit our needs as per #17. What do you think @tgermain?

It depends on how much time you think it will take to rewrite the client. 
I would say it is not a big deal to release a version with the old client as it already works today (with the custom fix we know).

I do not have much time currently but I will do my best to review what you assign me.

**Comment by charlex** [comment]
Thanks everyone!

**Pull request merged**
