### PR TITLE
Rewrite to use a vendored circleci v1.1 api client

### PR DESCRIPTION
**Pull request by ZymoticB**
This deletes the go.mod rewrite rule since it looks like those PRs aren't going to ever get merged. Additionally, some cleanup refactoring has gone on at the same time.

### CODE REVIEW

**Comment by ZymoticB** [comment]
I meant to open this to my own fork, sorry.

**Comment by mrolla** [comment]
If there is something you feel like merging upstream please open another PR!

**Comment by ZymoticB** [comment]
> If there is something you feel like merging upstream please open another PR!

I'm happy to upstream stuff (the code is in the open already). At this particular moment I'm trying to move pretty quickly so I forked to control my own releases. I've unleashed some of my own golang opinions on the codebase so the scope of my changes isn't particularly narrow as I wasn't explicitly planning to upstream right away. If you're open to the things I've done I'll definitely open a PR just let me know!

**Comment by bendrucker** [comment]
On quick glance the existing changes don't look PR friendly, as you mentioned. Stuff like using Uber's zap is obviously perfectly fine but not a conventional choice for Terraform providers, among other patterns introduced. 

That said, strong 👍🏻 for vendoring go-circleci and eliminating github.com/tgermain/go-circleci if you're up for submitting just that. No sense replacing one unmaintained fork with another, particularly with a separate org/user.

**Pull request closed without merging**
